/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.InsertController;

/**
 *
 * @author pethum priyankara
 */
public class AddPlayer extends javax.swing.JFrame {

    /**
     * Creates new form AddPlayer
     */
    public AddPlayer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        posi = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Name_Tf = new javax.swing.JTextField();
        ID_Tf = new javax.swing.JTextField();
        Age_Tf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Back_Btn = new javax.swing.JButton();
        Reset_Btn = new javax.swing.JButton();
        Submit_Btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        posi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posiActionPerformed(evt);
            }
        });
        jPanel1.add(posi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 372, 310, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD PLAYER DETAILS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 730, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 60));

        jLabel5.setFont(new java.awt.Font("Britannic Bold", 1, 36)); // NOI18N
        jLabel5.setText("Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 130, 30));

        jLabel6.setFont(new java.awt.Font("Britannic Bold", 1, 36)); // NOI18N
        jLabel6.setText("ID Number:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 30));

        jLabel7.setFont(new java.awt.Font("Britannic Bold", 1, 36)); // NOI18N
        jLabel7.setText("Age:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 130, 40));

        Name_Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_TfActionPerformed(evt);
            }
        });
        jPanel1.add(Name_Tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 310, 40));

        ID_Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_TfActionPerformed(evt);
            }
        });
        jPanel1.add(ID_Tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 310, 40));

        Age_Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_TfActionPerformed(evt);
            }
        });
        jPanel1.add(Age_Tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 310, 40));

        jLabel10.setFont(new java.awt.Font("Britannic Bold", 1, 36)); // NOI18N
        jLabel10.setText("Position:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 170, 30));

        Back_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Back_Btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Back_Btn.setText("Back");
        Back_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Back_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 130, 40));

        Reset_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Reset_Btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Reset_Btn.setText("Reset");
        Reset_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Reset_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, 130, 40));

        Submit_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Submit_Btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Submit_Btn.setText("Submit");
        Submit_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Submit_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add pic foot.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 900, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Name_TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_TfActionPerformed

    private void ID_TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_TfActionPerformed

    private void Age_TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Age_TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Age_TfActionPerformed

    private void Reset_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_BtnActionPerformed
       
        claerField();
    }//GEN-LAST:event_Reset_BtnActionPerformed

    public void claerField(){
        Name_Tf.setText("");       
        ID_Tf.setText("");
        Age_Tf.setText("");
        posi.setText("");
        
        
       
        
        
        
        
        
        
    
    }
    
    private void Back_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BtnActionPerformed
        Menu m1 = new Menu();
        m1.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_Back_BtnActionPerformed

    private void Submit_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_BtnActionPerformed
      
      
        
        
      
        
        
        InsertController.AddPlayer(Name_Tf.getText(), ID_Tf.getText(), Age_Tf.getText(),  posi.getText() );
    }//GEN-LAST:event_Submit_BtnActionPerformed

    private void posiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age_Tf;
    private javax.swing.JButton Back_Btn;
    private javax.swing.JTextField ID_Tf;
    private javax.swing.JTextField Name_Tf;
    private javax.swing.JButton Reset_Btn;
    private javax.swing.JButton Submit_Btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField posi;
    // End of variables declaration//GEN-END:variables
}
