/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DbConnection;
import Model.DbSearch;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author pethum priyankara
 */
public class ViewPlayer extends javax.swing.JFrame {

    /**
     * Creates new form ViewPlayer
     */
    public ViewPlayer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Search_Tf = new javax.swing.JTextField();
        View_Btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Position_Tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Name_Tf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Age_Tf = new javax.swing.JTextField();
        Back_Btn = new javax.swing.JButton();
        ViewAll_Btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VIEW PLAYER DETAILS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -10, 580, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 30));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter ID Number:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 190, 30));

        Search_Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_TfActionPerformed(evt);
            }
        });
        jPanel1.add(Search_Tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 270, 30));

        View_Btn.setBackground(new java.awt.Color(255, 102, 0));
        View_Btn.setForeground(new java.awt.Color(255, 255, 255));
        View_Btn.setText("View ");
        View_Btn.setMaximumSize(new java.awt.Dimension(59, 25));
        View_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(View_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 120, 30));

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Position:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 140, 30));

        Position_Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Position_TfActionPerformed(evt);
            }
        });
        jPanel1.add(Position_Tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 270, 30));

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 140, 30));

        Name_Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_TfActionPerformed(evt);
            }
        });
        jPanel1.add(Name_Tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 270, 30));

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Age:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 140, 30));

        Age_Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_TfActionPerformed(evt);
            }
        });
        jPanel1.add(Age_Tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 270, 30));

        Back_Btn.setBackground(new java.awt.Color(255, 102, 0));
        Back_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_Btn.setText("Back");
        Back_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Back_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 130, 40));

        ViewAll_Btn.setBackground(new java.awt.Color(0, 102, 255));
        ViewAll_Btn.setForeground(new java.awt.Color(255, 255, 255));
        ViewAll_Btn.setText("View All");
        ViewAll_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAll_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(ViewAll_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 580, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manchester-uk-nov-2022-city-260nw-2265675523.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 900, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Search_TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_TfActionPerformed

    private void Position_TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Position_TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Position_TfActionPerformed

    private void Name_TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_TfActionPerformed

    private void Age_TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Age_TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Age_TfActionPerformed

    private void ViewAll_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAll_BtnActionPerformed
        DeleteNview view = new DeleteNview();
        view.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_ViewAll_BtnActionPerformed

    private void Back_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BtnActionPerformed
        Menu m2 = new Menu();
        m2.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_Back_BtnActionPerformed

    private void View_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_BtnActionPerformed
        //Take values from database according to the user entered ID number
        try {
               
            ResultSet rs = new DbSearch().SearchPlayer(Search_Tf.getText());

            if(rs.next() == false){
                    
                    JOptionPane.showMessageDialog(this,"Player ID Not Found");
                }
                else{
                    //assign database login name to the variable
                    String name = rs.getString("Name"); 
                    String age = rs.getString("Age");
                    
                    String position = rs.getString("Position");
                    
                    Name_Tf.setText(name);
                    Age_Tf.setText(age);
                   
                    Position_Tf.setText(position);
                    
            }
    
            DbConnection.closeCon();
            } 
            catch (SQLException ex) { 
            //Logger.getLogger(LoginController.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_View_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age_Tf;
    private javax.swing.JButton Back_Btn;
    private javax.swing.JTextField Name_Tf;
    private javax.swing.JTextField Position_Tf;
    private javax.swing.JTextField Search_Tf;
    private javax.swing.JButton ViewAll_Btn;
    private javax.swing.JButton View_Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
